name: staging

on:
  push:
    branches-ignore: [ main ]

jobs:
  testsh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./test.sh
  testcmd:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwsh -File test_cmd.ps1
